spring.application.name=inbox-service
server.port=8082
server.servlet.context-path=/api/v1

spring.datasource.url=jdbc:mariadb://localhost:3306/inbox
spring.datasource.username=root
spring.datasource.password=

spring.jpa.open-in-view=false
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration

springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui

management.endpoints.web.exposure.include=health,info
management.endpoint.health.probes.enabled=true

logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO

inbox.security.internal-token=change-me
